# Fault Section Classification Using K-Nearest Neighbors (K-NN)

## Importing the libraries

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [27]:
faults = pd.read_csv('MSC_Dissertation_test_original3.csv')
faults

Fault_location  Fault_section  Fault_type  632_Active_PhaseA  \
0               0.0              0           0              1.130   
1               1.0              1           1              1.108   
2               2.3              2           1            134.500   
3               2.5              2           1             89.550   
4               2.7              2           1             67.220   
..              ...            ...         ...                ...   
152            11.9             11           4              1.130   
153            12.3             12           4              1.130   
154            12.5             12           4              1.130   
155            12.7             12           4              1.130   
156            12.9             12           4              1.130   

     632_Active_PhaseB  632_Active_PhaseC  633_Active_PhaseA  \
0               0.9087              1.189           0.142200   
1               0.8908              1.166           0.139400   
2             116.1000            127.500           0.000201   
3              77.3400             85.400           0.000087   
4              58.0600             64.360           0.000048   
..                 ...                ...                ...   
152            25.0900              1.194           0.142200   
153            21.0300              1.195           0.142200   
154            19.4700              1.195           0.142200   
155            18.1300              1.195           0.142200   
156            15.9600              1.196           0.142200   

     633_Active_PhaseB  633_Active_PhaseC  692_Active_PhaseA  ...  \
0             0.104900           0.104900             0.4613  ...   
1             0.102800           0.102900             0.4522  ...   
2             0.000184           0.000046             0.4610  ...   
3             0.000088           0.000021             0.4611  ...   
4             0.000052           0.000013             0.4612  ...   
..                 ...                ...                ...  ...   
152           0.104900           0.104900             0.4613  ...   
153           0.104900           0.104900             0.4613  ...   
154           0.104900           0.104900             0.4613  ...   
155           0.104900           0.104900             0.4613  ...   
156           0.104900           0.104900             0.4613  ...   

     692_Active_PhaseC  671_Active_PhaseA  671_Active_PhaseB  \
0               0.2534            -0.9627            -0.4158   
1               0.2484            -0.9437            -0.4076   
2               0.2533            -0.9622            -0.4157   
3               0.2533            -0.9624            -0.4157   
4               0.2533            -0.9624            -0.4157   
..                 ...                ...                ...   
152             0.2534            -0.9627            -0.4158   
153             0.2534            -0.9627            -0.4158   
154             0.2534            -0.9627            -0.4158   
155             0.2534            -0.9627            -0.4158   
156             0.2534            -0.9627            -0.4158   

     671_Active_PhaseC  645_Active_PhaseA  645_Active_PhaseB  \
0              -0.8718                  0          -0.331700   
1              -0.8545                  0          -0.325300   
2              -0.8714                  0          -0.331600   
3              -0.8716                  0          -0.331700   
4              -0.8716                  0          -0.331700   
..                 ...                ...                ...   
152            -0.8718                  0          -0.003662   
153            -0.8718                  0          -4.557000   
154            -0.8718                  0          -5.264000   
155            -0.8718                  0          -5.739000   
156            -0.8718                  0          -6.250000   

     645_Active_PhaseC  684_Active_Phase

In [29]:
X = faults.iloc[:, 2:21].values
y = faults.iloc[:, 1].values

## Splitting the dataset into the Training set and Test set

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101)

In [36]:
print(X_train)

[[ 3.000e+00  3.774e+00  9.793e-01 ... -1.471e-02  0.000e+00 -2.323e-01]
 [ 2.000e+00  2.146e+01  9.408e-01 ... -5.386e-05  0.000e+00 -2.677e-01]
 [ 2.000e+00  1.130e+00  9.087e-01 ... -1.243e-01  0.000e+00 -1.667e-01]
 ...
 [ 3.000e+00  5.392e+01  9.130e-01 ... -1.243e-01  0.000e+00 -1.667e-01]
 [ 1.000e+00  1.120e+01  5.871e+00 ... -1.605e-06  0.000e+00 -6.200e-06]
 [ 3.000e+00  4.418e+00  9.931e-01 ... -5.558e-03  0.000e+00 -2.479e-01]]


In [37]:
print(y_train)

[ 7  4 10  2  6 10  9  5  9  8  4  4 12  7  6  2  9 12 10  8  8 10 12  7
  8  1  6  7 12  4 11  9 10  8  3  6  4  6  2  2 12  6  5 12  7 10  2  3
  4  6  4  4  9  2  9  8 10 11 10 11  6  7  4  9  6  1 11  7  6  6  7  6
  9 11  7 11  3 12  9  7  6  4  4 10 10  8  8 12  8  4  8 11  2  9  0 11
 10 12  4  7 11  2  8 11 12  7 11  2  4 10  8  2 11  8 11  6  1  8 12  4
  9 10  2  5  7]


In [38]:
print(X_test)

[[ 3.000e+00  5.768e+00  9.749e-01  1.180e+00  1.422e-01  1.049e-01
   1.049e-01  5.087e-02  8.757e-02  3.373e-01 -2.974e+00 -5.761e-01
  -8.981e-01  0.000e+00 -3.317e-01 -7.943e-02 -1.437e+00  0.000e+00
  -2.344e-01]
 [ 2.000e+00  9.620e+01  4.864e+01  1.220e+00  1.670e-03  1.170e-03
   1.409e-01  4.611e-01  5.778e-02  2.534e-01 -9.623e-01 -4.158e-01
  -8.718e-01  0.000e+00 -3.317e-01 -7.945e-02 -1.243e-01  0.000e+00
  -1.667e-01]
 [ 2.000e+00  1.380e+01  8.080e-01  1.209e+00  1.422e-01  1.049e-01
   1.049e-01  9.417e-03  1.296e-03  3.833e-01 -2.078e+00 -1.517e-01
  -1.071e+00  0.000e+00 -3.317e-01 -7.944e-02 -2.555e-03  0.000e+00
  -2.526e-01]
 [ 3.000e+00  5.470e+00  9.951e-01  1.188e+00  1.422e-01  1.049e-01
   1.049e-01  1.341e-02  9.079e-02  3.768e-01 -1.650e+00 -6.020e-01
  -9.496e-01  0.000e+00 -3.317e-01 -7.943e-02 -6.887e-05  0.000e+00
  -2.600e-01]
 [ 1.000e+00  1.130e+00  7.328e+01  5.171e+01  1.422e-01  1.049e-01
   1.049e-01  4.613e-01  5.777e-02  2.533e-01 -9.627e-01 -4.

In [39]:
print(y_test)

[ 9  2  7  8 11 10 12  9  7 11  2  6 12  9  6  3  2  9  2  1 11  4  2  5
 12 10 10  8 12 12  9  7]


## Feature Scaling

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [41]:
print(X_train)

[[ 0.45232785 -0.29035977 -0.49171244 ...  0.41380749  0.
  -0.32487981]
 [-0.4175334   0.67094883 -0.49368618 ...  0.44185244  0.
  -0.58154658]
 [-0.4175334  -0.43407231 -0.49533182 ...  0.20410381  0.
   0.15075125]
 ...
 [ 0.45232785  2.43528657 -0.49511138 ...  0.20410381  0.
   0.15075125]
 [-1.28739465  0.11327461 -0.24093446 ...  0.44195244  0.
   1.35936023]
 [ 0.45232785 -0.25535566 -0.49100497 ...  0.43132011  0.
  -0.4379872 ]]


In [42]:
print(X_test)

[[ 4.52327850e-01 -1.81977469e-01 -4.91938009e-01 -2.93297185e-01
  -1.03418618e-01 -1.29501810e-01 -8.93460945e-02 -7.17696269e-01
  -2.40864889e-01  3.46389520e-02 -1.81472248e+00  4.95709085e-02
   2.94277571e-01  0.00000000e+00  2.20484124e-01  1.64322738e-01
  -2.30778611e+00  0.00000000e+00 -3.40105808e-01]
 [-4.17533400e-01  4.73338268e+00  1.95166189e+00 -2.90620295e-01
  -4.45552206e-01 -4.25723641e-01  8.01786763e-02 -5.91887206e-02
  -2.86054724e-01 -2.14023534e-01  4.12579679e-01  3.13101727e-01
   3.45190047e-01  0.00000000e+00  2.20484124e-01  1.64296715e-01
   2.04103814e-01  0.00000000e+00  1.50751249e-01]
 [-4.17533400e-01  2.54595566e-01 -5.00494307e-01 -2.91356440e-01
  -1.03418618e-01 -1.29501810e-01 -8.93460945e-02 -7.84237266e-01
  -3.71737928e-01  1.70973569e-01 -8.22694477e-01  7.47278202e-01
  -4.04284061e-02  0.00000000e+00  2.20484124e-01  1.64309727e-01
   4.37066440e-01  0.00000000e+00 -4.72064426e-01]
 [ 4.52327850e-01 -1.98175024e-01 -4.90902435e-01 -2.92

## Training the K-NN model on the Training set

In [43]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 1, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

## Predicting a new result

In [44]:
print(classifier.predict(sc.transform([[1,67.220,58.0600,64.360,0.00004835,0.0000518,0.000001254,0.4612,0.05777,0.2533,-0.9624,-0.4157,-0.8716,0,-0.331700,-0.07942,-0.1243,0,-0.1667]])))

[2]


## Predicting the Test set results

In [45]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 9  9]
 [ 2  2]
 [ 7  7]
 [ 8  8]
 [11 11]
 [11 10]
 [12 12]
 [10  9]
 [ 6  7]
 [11 11]
 [11  2]
 [ 6  6]
 [12 12]
 [ 9  9]
 [ 6  6]
 [ 3  3]
 [ 2  2]
 [ 9  9]
 [ 2  2]
 [ 1  1]
 [11 11]
 [ 4  4]
 [ 2  2]
 [ 4  5]
 [12 12]
 [10 10]
 [10 10]
 [ 8  8]
 [12 12]
 [12 12]
 [ 9  9]
 [ 7  7]]


## Making the Confusion Matrix

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 0 4 1 0 0]
 [0 0 0 0 0 0 0 0 0 2 1 0]
 [0 0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 5]]


0.84375

In [47]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         1
           2       1.00      0.80      0.89         5
           3       1.00      1.00      1.00         1
           4       0.50      1.00      0.67         1
           5       0.00      0.00      0.00         1
           6       0.67      1.00      0.80         2
           7       1.00      0.67      0.80         3
           8       1.00      1.00      1.00         2
           9       1.00      0.80      0.89         5
          10       0.67      0.67      0.67         3
          11       0.60      1.00      0.75         3
          12       1.00      1.00      1.00         5

    accuracy                           0.84        32
   macro avg       0.79      0.83      0.79        32
weighted avg       0.86      0.84      0.84        32



C:\Users\buhwhy\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [48]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
mean_absolute_error(y_test,y_pred)

0.40625

In [49]:
mean_squared_error(y_test,y_pred)

2.65625

## The End