# Faults Location Prediction Using Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

### Importing the dataset

In [3]:
faults = pd.read_csv('MSC_Dissertation_test_original3.csv')
faults

Fault_location  Fault_section  Fault_type  632_Active_PhaseA  \
0               0.0              0           0              1.130   
1               1.0              1           1              1.108   
2               2.3              2           1            134.500   
3               2.5              2           1             89.550   
4               2.7              2           1             67.220   
..              ...            ...         ...                ...   
152            11.9             11           4              1.130   
153            12.3             12           4              1.130   
154            12.5             12           4              1.130   
155            12.7             12           4              1.130   
156            12.9             12           4              1.130   

     632_Active_PhaseB  632_Active_PhaseC  633_Active_PhaseA  \
0               0.9087              1.189           0.142200   
1               0.8908              1.166           0.139400   
2             116.1000            127.500           0.000201   
3              77.3400             85.400           0.000087   
4              58.0600             64.360           0.000048   
..                 ...                ...                ...   
152            25.0900              1.194           0.142200   
153            21.0300              1.195           0.142200   
154            19.4700              1.195           0.142200   
155            18.1300              1.195           0.142200   
156            15.9600              1.196           0.142200   

     633_Active_PhaseB  633_Active_PhaseC  692_Active_PhaseA  ...  \
0             0.104900           0.104900             0.4613  ...   
1             0.102800           0.102900             0.4522  ...   
2             0.000184           0.000046             0.4610  ...   
3             0.000088           0.000021             0.4611  ...   
4             0.000052           0.000013             0.4612  ...   
..                 ...                ...                ...  ...   
152           0.104900           0.104900             0.4613  ...   
153           0.104900           0.104900             0.4613  ...   
154           0.104900           0.104900             0.4613  ...   
155           0.104900           0.104900             0.4613  ...   
156           0.104900           0.104900             0.4613  ...   

     692_Active_PhaseC  671_Active_PhaseA  671_Active_PhaseB  \
0               0.2534            -0.9627            -0.4158   
1               0.2484            -0.9437            -0.4076   
2               0.2533            -0.9622            -0.4157   
3               0.2533            -0.9624            -0.4157   
4               0.2533            -0.9624            -0.4157   
..                 ...                ...                ...   
152             0.2534            -0.9627            -0.4158   
153             0.2534            -0.9627            -0.4158   
154             0.2534            -0.9627            -0.4158   
155             0.2534            -0.9627            -0.4158   
156             0.2534            -0.9627            -0.4158   

     671_Active_PhaseC  645_Active_PhaseA  645_Active_PhaseB  \
0              -0.8718                  0          -0.331700   
1              -0.8545                  0          -0.325300   
2              -0.8714                  0          -0.331600   
3              -0.8716                  0          -0.331700   
4              -0.8716                  0          -0.331700   
..                 ...                ...                ...   
152            -0.8718                  0          -0.003662   
153            -0.8718                  0          -4.557000   
154            -0.8718                  0          -5.264000   
155            -0.8718                  0          -5.739000   
156            -0.8718                  0          -6.250000   

     645_Active_PhaseC  684_Active_Phase

In [46]:
X = faults.iloc[:, 1:21].values
y = faults.iloc[:, 0].values

In [47]:
print(X)

[[ 0.000e+00  0.000e+00  1.130e+00 ... -1.243e-01  0.000e+00 -1.667e-01]
 [ 1.000e+00  1.000e+00  1.108e+00 ... -1.219e-01  0.000e+00 -1.634e-01]
 [ 2.000e+00  1.000e+00  1.345e+02 ... -1.243e-01  0.000e+00 -1.666e-01]
 ...
 [ 1.200e+01  4.000e+00  1.130e+00 ... -1.243e-01  0.000e+00 -1.667e-01]
 [ 1.200e+01  4.000e+00  1.130e+00 ... -1.243e-01  0.000e+00 -1.667e-01]
 [ 1.200e+01  4.000e+00  1.130e+00 ... -1.243e-01  0.000e+00 -1.667e-01]]


In [48]:
print(y)

[ 0.    1.    2.3   2.5   2.7   2.9   3.    4.25  4.5   4.75  4.9   5.
  6.3   6.5   6.7   6.9   7.3   7.5   7.7   7.9   8.3   8.5   8.7   8.9
  9.3   9.5   9.7   9.9  10.3  10.5  10.7  10.9  11.3  11.5  11.7  11.9
 12.3  12.5  12.7  12.9   1.    2.3   2.5   2.7   2.9   3.    4.25  4.5
  4.75  4.9   5.    6.3   6.5   6.7   6.9   7.3   7.5   7.7   7.9   8.3
  8.5   8.7   8.9   9.3   9.5   9.7   9.9  10.3  10.5  10.7  10.9  11.3
 11.5  11.7  11.9  12.3  12.5  12.7  12.9   1.    2.3   2.5   2.7   2.9
  3.    4.25  4.5   4.75  4.9   5.    6.3   6.5   6.7   6.9   7.3   7.5
  7.7   7.9   8.3   8.5   8.7   8.9   9.3   9.5   9.7   9.9  10.3  10.5
 10.7  10.9  11.3  11.5  11.7  11.9  12.3  12.5  12.7  12.9   1.    2.3
  2.5   2.7   2.9   3.    4.25  4.5   4.75  4.9   5.    6.3   6.5   6.7
  6.9   7.3   7.5   7.7   7.9   8.3   8.5   8.7   8.9   9.3   9.5   9.7
  9.9  10.3  10.5  10.7  10.9  11.3  11.5  11.7  11.9  12.3  12.5  12.7
 12.9 ]


### One Hot Encoding

In [49]:
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [50]:
print(y)

[ 0.    1.    2.3   2.5   2.7   2.9   3.    4.25  4.5   4.75  4.9   5.
  6.3   6.5   6.7   6.9   7.3   7.5   7.7   7.9   8.3   8.5   8.7   8.9
  9.3   9.5   9.7   9.9  10.3  10.5  10.7  10.9  11.3  11.5  11.7  11.9
 12.3  12.5  12.7  12.9   1.    2.3   2.5   2.7   2.9   3.    4.25  4.5
  4.75  4.9   5.    6.3   6.5   6.7   6.9   7.3   7.5   7.7   7.9   8.3
  8.5   8.7   8.9   9.3   9.5   9.7   9.9  10.3  10.5  10.7  10.9  11.3
 11.5  11.7  11.9  12.3  12.5  12.7  12.9   1.    2.3   2.5   2.7   2.9
  3.    4.25  4.5   4.75  4.9   5.    6.3   6.5   6.7   6.9   7.3   7.5
  7.7   7.9   8.3   8.5   8.7   8.9   9.3   9.5   9.7   9.9  10.3  10.5
 10.7  10.9  11.3  11.5  11.7  11.9  12.3  12.5  12.7  12.9   1.    2.3
  2.5   2.7   2.9   3.    4.25  4.5   4.75  4.9   5.    6.3   6.5   6.7
  6.9   7.3   7.5   7.7   7.9   8.3   8.5   8.7   8.9   9.3   9.5   9.7
  9.9  10.3  10.5  10.7  10.9  11.3  11.5  11.7  11.9  12.3  12.5  12.7
 12.9 ]


### Splitting the dataset into the Training set and Test set

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

### Feature Scaling

In [52]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Initializing the ANN

In [53]:
ANN = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [54]:
ANN.add(tf.keras.layers.Dense(units=23, activation='relu'))
ANN.add(tf.keras.layers.Dense(units=23, activation='relu'))


### Adding the second hidden layer

In [55]:
ANN.add(tf.keras.layers.Dense(units=23, activation='relu'))



### Adding the output layer

In [56]:
ANN.add(tf.keras.layers.Dense(units=1))

### Compiling the ANN

In [57]:
ANN.compile(optimizer = 'adam', loss = 'mse', metrics = ['accuracy'])

### Training the ANN on the Training set

In [58]:
ANN.fit(X_train, y_train, batch_size = 32, epochs = 150)

Epoch 1/150
5/5 [==============================] - 1s 3ms/step - loss: 75.3998 - accuracy: 0.0071
Epoch 2/150
5/5 [==============================] - 0s 4ms/step - loss: 73.0327 - accuracy: 0.0071
Epoch 3/150
5/5 [==============================] - 0s 4ms/step - loss: 70.7817 - accuracy: 0.0071
Epoch 4/150
5/5 [==============================] - 0s 4ms/step - loss: 68.5419 - accuracy: 0.0071
Epoch 5/150
5/5 [==============================] - 0s 2ms/step - loss: 66.1492 - accuracy: 0.0213
Epoch 6/150
5/5 [==============================] - 0s 4ms/step - loss: 63.4977 - accuracy: 0.0213
Epoch 7/150
5/5 [==============================] - 0s 4ms/step - loss: 60.5031 - accuracy: 0.0284
Epoch 8/150
5/5 [==============================] - 0s 4ms/step - loss: 57.1611 - accuracy: 0.0284
Epoch 9/150
5/5 [==============================] - 0s 5ms/step - loss: 53.2168 - accuracy: 0.0284
Epoch 10/150
5/5 [==============================] - 0s 1ms/step - loss: 48.9357 - accuracy: 0.0284
Epoch 11/150
5/5 [=

##  Making the predictions and evaluating the model

### Predicting the result of a single observation

In [59]:
print(ANN.predict(sc.transform([[2,1,67.220,58.0600,64.360,0.00004835,0.0000518,0.00001254,0.4612,0.05777,0.2533,-0.9624,-0.4157,-0.8716,0,-0.331700,-0.07942,-0.1243,0,-0.1667]])))

1/1 [==============================] - 0s 90ms/step
[[2.61487]]


### Predicting the Test set results

In [41]:
y_pred = ANN.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

1/1 [==============================] - 0s 5ms/step
[[ 4.45870972  4.75      ]
 [ 4.04813051  3.        ]
 [ 7.6732707   7.3       ]
 [ 8.45492172  8.5       ]
 [11.64297962 11.5       ]
 [10.35725117 10.5       ]
 [ 7.56625605  7.5       ]
 [ 7.54782295  7.9       ]
 [ 7.59320068  7.3       ]
 [ 8.45492172  8.7       ]
 [ 7.26322556  7.9       ]
 [ 7.82573938  7.5       ]
 [ 8.31591034  6.9       ]
 [10.56585026 10.7       ]
 [ 8.0841732   9.3       ]
 [10.54483604 10.7       ]]


In [60]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
mean_absolute_error(y_test,y_pred)

0.4302359342575073

In [61]:
mean_squared_error(y_test,y_pred)

0.35479727160356567

## The End